openapi: 3.0.0
info:
  title: Admin Panel API
  version: 1.0.0
  description: API
paths:
  /auth/register:
    post:
      $ref: "./endpoints/auth.yaml#/register"

  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"

  /auth/refresh:
    post:
      $ref: "./endpoints/auth.yaml#/refresh"

  /people:
    get:
      $ref: "./endpoints/people.yaml#/getAllPeople"

    post:
      $ref: "./endpoints/people.yaml#/createPerson"

  /people/{personId}:
    delete:
      $ref: "./endpoints/people.yaml#/deletePerson"
